language: php

php:
    - 7.1
    - 7.2
    - 7.3

before_install:
    - composer self-update

before_script:
    - composer install --prefer-source

script:
    - vendor/bin/phpunit -v

notifications:
  email: "douglas@usemarkup.com"

sudo: false
dist: trusty
